SELECT TOP (1000) [Id]
      ,[Id_Nazione]
      ,[Nome]
      ,[Squadre]
  FROM [Marcatori].[dbo].[Leghe] 
  INSERT INTO [dbo].[Leghe] (Id, Id_Nazione, Nome, Squadre)
  VALUES
(1, 1, 'Liga Profesional de Fútbol', 'River Plate, Boca Juniors, Racing Club, Independiente'),
(2, 1, 'Primera Nacional', 'Belgrano, Quilmes, Instituto, All Boys'),
(3, 2, 'División Profesional', 'The Strongest, Bolívar, Always Ready, Oriente Petrolero'),
(4, 2, 'Copa Simón Bolívar', 'Universitario de Vinto, Torre Fuerte, Stormers, FATIC'),
(5, 3, 'Campeonato Brasileiro Série A', 'Palmeiras, Flamengo, São Paulo, Corinthians'),
(6, 3, 'Campeonato Brasileiro Série B', 'Santos, Sport Recife, Ceará, Vila Nova'),
(7, 4, 'Primera División de Chile', 'Colo-Colo, Universidad de Chile, Universidad Católica, Unión Española'),
(8, 4, 'Primera B de Chile', 'Santiago Wanderers, Deportes Iquique, Cobreloa, Deportes Antofagasta'),
(9, 5, 'Categoría Primera A', 'Atlético Nacional, Millonarios, América de Cali, Junior'),
(10, 5, 'Categoría Primera B', 'Cúcuta Deportivo, Deportes Quindío, Real Cartagena, Tigres FC'),
(11, 6, 'Liga FPD', 'Saprissa, Alajuelense, Herediano, Cartaginés'),
(12, 6, 'Liga de Ascenso', 'Belén FC, Escorpiones, Guanacasteca, Carmelita'),
(13, 7, 'Serie A Ecuador', 'Barcelona SC, Emelec, LDU Quito, Independiente del Valle'),
(14, 7, 'Serie B Ecuador', 'Manta FC, América de Quito, El Nacional, Chacaritas'),
(15, 8, 'Liga MX', 'Club América, Chivas Guadalajara, Cruz Azul, Tigres UANL'),
(16, 8, 'Liga de Expansión MX', 'Atlante, Leones Negros, Atlético Morelia, Cancún FC'),
(17, 9, 'Primera División de Paraguay', 'Olimpia, Cerro Porteño, Libertad, Guaraní'),
(18, 9, 'División Intermedia', 'Sportivo Luqueño, San Lorenzo, Atyrá FC, Fernando de la Mora'),
(19, 10, 'Liga 1 Perú', 'Alianza Lima, Universitario, Sporting Cristal, FBC Melgar'),
(20, 10, 'Liga 2 Perú', 'Juan Aurich, Comerciantes Unidos, Alianza Universidad, Santos FC'),
(21, 11, 'Major League Soccer', 'LA Galaxy, Inter Miami, Seattle Sounders, Atlanta United'),
(22, 11, 'USL Championship', 'Louisville City, Sacramento Republic, Tampa Bay Rowdies, Phoenix Rising'),
(23, 12, 'Primera División Uruguaya', 'Peñarol, Nacional, Defensor Sporting, Danubio'),
(24, 12, 'Segunda División Uruguay', 'Miramar Misiones, Atenas, Rampla Juniors, Oriental'),
(25, 13, 'Primera División Venezuela', 'Caracas FC, Deportivo Táchira, Zamora, Monagas'),
(26, 13, 'Segunda División Venezuela', 'Angostura, Ureña SC, Titanes FC, Bolívar SC'),
(27, 24, 'Serie A', 'Juventus, Inter, AC Milan, Napoli'), 
(28, 24, 'Serie B', 'Palermo, Lecce, Brescia, Benevento'),
(29, 20, 'Ligue 1', 'Paris Saint-Germain, Marseille, Lyon, Monaco'),
(30, 20, 'Ligue 2', 'Toulouse, Ajaccio, Grenoble, Valenciennes'),
(31, 21, 'Bundesliga', 'Bayern Monaco, Borussia Dortmund, RB Leipzig, Bayer Leverkusen'),
(32, 21, '2. Bundesliga', 'St. Pauli, Hannover, Karlsruhe, Nuremberg'),
(33, 32, 'La Liga', 'Real Madrid, Barcelona, Atlético Madrid, Sevilla'),
(34, 32, 'Segunda División', 'Espanyol, Sporting Gijón, Mallorca, Girona'),
(35, 23, 'Premier League', 'Manchester United, Liverpool, Chelsea, Arsenal'),
(36, 23, 'Championship', 'West Brom, Sunderland, Hull City, Bristol City'),
(37, 30, 'Premiership Scozia', 'Celtic, Rangers, Aberdeen, Hearts'),
(38, 30, 'Scottish Championship', 'Dundee, Queen of the South, Raith Rovers, Partick Thistle'),
(39, 22, 'Super League Grecia', 'Olympiacos, Panathinaikos, AEK Athens, PAOK'),
(40, 22, 'Football League', 'Aris, Atromitos, Lamia, Volos'),
(41, 19, 'Danish Superliga', 'Copenhagen, Midtjylland, Brøndby, Aalborg'),
(42, 19, '1st Division', 'Vejle, Viborg, Silkeborg, Fredericia'),
(43, 16, 'Belgian Pro League', 'Club Brugge, Anderlecht, Genk, Standard Liège'),
(44, 16, 'Challenger Pro League', 'Westerlo, RWDM, Lommel, Seraing'),
(45, 17, 'Prva Liga Bulgaria', 'Ludogorets, CSKA Sofia, Levski Sofia, Botev Plovdiv'),
(46, 17, 'Vtora Liga', 'Montana, Botev Vratsa, Septemvri, Pirin'),
(47, 18, 'Prva HNL Croazia', 'Dinamo Zagreb, Hajduk Split, Rijeka, Osijek'),
(48, 18, 'Druga HNL', 'Šibenik, Istra 1961, Cibalia, Hrvatski Dragovoljac'),
(49, 46, 'J1 League', 'Kawasaki Frontale, Yokohama F. Marinos, Urawa Red Diamonds, Gamba Osaka'),
(50, 46, 'J2 League', 'Omiya Ardija, V-Varen Nagasaki, Machida Zelvia, Tokushima Vortis'),
(51, 43, 'Chinese Super League', 'Guangzhou FC, Shanghai Port, Beijing Guoan, Shandong Taishan'),
(52, 43, 'China League One', 'Qingdao Hainiu, Meizhou Hakka, Nantong Zhiyun, Dalian Pro'),
(53, 44, 'K League 1', 'Jeonbuk Hyundai, Ulsan Hyundai, FC Seoul, Suwon Samsung'),
(54, 44, 'K League 2', 'Gimcheon Sangmu, Busan IPark, Seoul E-Land, Cheonan City'),
(55, 45, 'UAE Pro League', 'Al Ain, Al Wahda, Shabab Al Ahli, Al Jazira'),
(56, 45, 'UAE Division 1', 'Hatta, Emirates, Al Dhaid, Masfut'),
(57, 42, 'Saudi Professional League', 'Al Hilal, Al Nassr, Al Ittihad, Al Ahli'),
(58, 42, 'Saudi First Division', 'Al Adalah, Al Batin, Al Khaleej, Al Fateh'),
(59, 47, 'Indian Super League', 'Mumbai City, Mohun Bagan, Bengaluru FC, Kerala Blasters'),
(60, 47, 'I-League', 'Churchill Brothers, Real Kashmir, Sreenidi Deccan, RoundGlass Punjab'),
(61, 48, 'Liga 1 Indonesia', 'Persija Jakarta, Bali United, PSM Makassar, Persebaya Surabaya'),
(62, 48, 'Liga 2 Indonesia', 'RANS Nusantara, Persis Solo, PSMS Medan, Persekat'),
(63, 49, 'Persian Gulf Pro League', 'Persepolis, Esteghlal, Sepahan, Tractor'),
(64, 49, 'Azadegan League', 'Mes Rafsanjan, Havadar, Fajr Sepasi, Naft Masjed Soleyman'),
(65, 50, 'Israeli Premier League', 'Maccabi Haifa, Hapoel Be’er Sheva, Maccabi Tel Aviv, Beitar Jerusalem'),
(66, 50, 'Liga Leumit', 'Hapoel Jerusalem, Hapoel Haifa, Bnei Sakhnin, Ironi Kiryat Shmona'),
(67, 51, 'Malaysia Super League', 'Johor Darul Ta’zim, Terengganu, Sabah, Selangor'),
(68, 51, 'Malaysia Premier League', 'Kedah, Negeri Sembilan, PDRM, Penang'),
(69, 52, 'Oman Professional League', 'Al-Seeb, Dhofar, Al-Nasr, Suwaiq'),
(70, 52, 'Oman First Division', 'Al-Shabab, Al-Musannah, Al-Oruba, Bowsher'),
(71, 53, 'Qatar Stars League', 'Al Sadd, Al Duhail, Al Rayyan, Al Ahli'),
(72, 53, 'Qatar Second Division', 'Al Shahaniya, Al Kharaitiyat, Muaither, Al Markhiya'),
(73, 54, 'Thai League 1', 'Buriram United, Muangthong United, Port FC, Chiangrai United'),
(74, 54, 'Thai League 2', 'Nakhon Ratchasima, Lampang, Rayong, Khon Kaen United'),
(75, 55, 'V-League 1', 'Hanoi FC, Hoang Anh Gia Lai, Viettel, Becamex Binh Duong'),
(76, 55, 'V-League 2', 'Dong A Thanh Hoa, Haiphong, Nam Dinh, Can Tho'),
(77, 38, 'A-League Men', 'Sydney FC, Melbourne City, Brisbane Roar, Western Sydney Wanderers'),
(78, 38, 'Y-League', 'Perth Glory Youth, Melbourne Victory Youth, Sydney FC Youth, Brisbane Roar Youth'),
(79, 39, 'Solomon Islands S-League', 'Kossa, Solomon Warriors, Marist, Henderson Eels'),
(80, 40, 'New Caledonia Super Ligue', 'Hienghène Sport, AS Magenta, AS Mont-Dore, AS Lössi'),
(81, 41, 'New Zealand Football Championship', 'Team Wellington, Auckland City, Wellington Phoenix Reserves, Hawke’s Bay United'),
(82, 56, 'Ligue 1 Algérie', 'CR Belouizdad, JS Kabylie, MC Alger, USM Alger'),
(83, 56, 'Ligue 2 Algérie', 'ASO Chlef, WA Tlemcen, NC Magra, RC Arbaâ'),
(84, 57, 'Elite One Camerun', 'Coton Sport, Union Douala, PWD Bamenda, Canon Yaoundé'),
(85, 57, 'Elite Two Camerun', 'Dragon Club, Eding Sport, Colombe, Les Astres'),
(86, 58, 'Ligue 1 Côte d-Ivoire', 'ASEC Mimosas, Africa Sports, SOA, San Pedro'),
(87, 58, 'Ligue 2 Côte d-Ivoire', 'Bouaké FC, Stella Club, RC Abidjan, SC Gagnoa'),
(88, 59, 'Egyptian Premier League', 'Al Ahly, Zamalek, Pyramids FC, Ismaily'),
(89, 59, 'Egyptian Second Division', 'Al Masry, El Gouna, Aswan, Nogoom'),
(90, 60, 'Ghana Premier League', 'Accra Hearts of Oak, Asante Kotoko, Ashanti Gold, Medeama'),
(91, 60, 'Division One League', 'Bechem United, Liberty Professionals, King Faisal, Dreams FC'),
(92, 61, 'Kenya Premier League', 'Gor Mahia, AFC Leopards, Sofapaka, Bandari'),
(93, 61, 'National Super League', 'Kariobangi Sharks, Nairobi City Stars, Zoo FC, Posta Rangers'),
(94, 62, 'Botola Pro', 'Wydad Casablanca, Raja Casablanca, FUS Rabat, RS Berkane'),
(95, 62, 'Botola 2', 'OC Khouribga, Moghreb Tétouan, Ittihad Tanger, Hassania Agadir'),
(96, 63, 'Nigeria Professional Football League', 'Enyimba, Kano Pillars, Shooting Stars, Rivers United'),
(97, 63, 'Nigeria National League', 'Heartland, Plateau United, Akwa United, Gombe United'),
(98, 64, 'Ligue 1 Senegal', 'Casa Sports, ASC Diaraf, Génération Foot, Teungueth FC'),
(99, 64, 'Ligue 2 Senegal', 'US Gorée, ASC Linguère, ASC Niarry Tally, Guédiawaye FC'),
(100, 65, 'Premier Soccer League Sudafrica', 'Mamelodi Sundowns, Orlando Pirates, Kaizer Chiefs, SuperSport United'),
(101, 65, 'National First Division', 'Maritzburg United, Chippa United, Baroka, TS Galaxy'),
(102, 66, 'Ligue Professionnelle 1 Tunisia', 'Espérance, Étoile du Sahel, Club Africain, CS Sfaxien'),
(103, 66, 'Ligue Professionnelle 2', 'US Monastir, Olympique Béja, AS Gabès, JS Kairouan'),
(104, 67, 'Zambia Super League', 'Zesco United, Nkana, Green Buffaloes, Forest Rangers'),
(105, 67, 'Division One League', 'Kabwe Warriors, Nchanga Rangers, Power Dynamos, Red Arrows'),
(106, 68, 'Zimbabwe Premier Soccer League', 'Dynamos, Highlanders, CAPS United, Ngezi Platinum'),
(107, 68, 'Division One League', 'Black Rhinos, Chicken Inn, Hwange, Bulawayo Chiefs')

    