  INSERT INTO [dbo].[Continenti](Id,Nome)
  VALUES 
  (1,'Americhe'),
  (2,'Europa'),
  (3,'Oceania'),
  (4,'Asia'),
  (5,'Africa')
 
 att river plate:  

  Matías Suárez,
  Federico Girotti,
  Lucas Beltrán, 
  Esequiel Barco

  att boca juniors:

  Darío Benedetto,
  Luis Vázquez, 
  Exequiel Zeballos,
  Sebastián Villa
  att racing club: 
  Héctor Fertoli ,
  Lisandro López , David Barbona , 
  Jonathan Cristaldo 

  att independiente: 
  
  Silvio Romero,
  Leandro Fernández,
  Cecilio Domínguez,
  Kevin Gauna

  att belgrano:
  
  Lucas Melano,
  Federico Bravo ,
  Alexis Ferrero , 
    Juan Brunetta
  
  att quilmes:
  
  Maximiliano Caire ,
  Lautaro Parisi, 
  Gabriel Graciani
 
 att instituto:
  
  Lucas Gamba,
  Pablo Vegetti,
  Federico Andrada,
  Santiago Silva 
  
  att all boys:
  
  Walter Bou,
  Luciano Ferreyra,
  Emanuel Dening
  
The Strongest:

Jeyson Chura
Boris Cespedes
Saúl Torres 
Juan Carlos Arce 
Jair Reinoso 

Bolívar:

Rodrigo Ramallo
Ramiro Vaca 
Fernando Saucedo 
Juan Miguel Callejón 
Leonardo Vaca

Always Ready:

Mauricio Aguirre
Gilbert Álvarez
Gilbert Álvarez 
Jeyson Chura 
Carlos Saucedo 

Oriente Petrolero:

Martín Prost
Damián Lizio 
Rodrigo Ramallo
José Alfredo Castillo 
Henry Vaca

Universitario de Vinto:

Pablo Pedraza 
Carlos Saucedo 
Nelson Cabrera
Jorge Arias

Torre Fuerte:

 Juan Carlos Gutiérrez
 Ronald Mamani
 Víctor Flores 

 Stormers:

 Diego Flores
 Erick Mamani

FATIC:

Wilmer Chacón
José Escobar

Palmeiras:

Endrick
Rony
Dudu 
Raphael Veiga 

Flamengo: 

Gabriel Barbosa
Pedro
Everton Cebolinha

São Paulo: 

Jonathan Calleri
Luciano
Talles 

Corinthians:

Róger Guedes
Yuri Alberto
Gustavo Mosquito

Santos:

Neymar Jr
Marcos Leonardo
Ângelo
Marinho
Allan Aleixo 

Sport Recife:

Mikael
Everaldo
Pedro Henrique
Kayke

Ceará:

Vina 
Wescley
Rick 
Lima 

Vila Nova: 

Matheus Barbosa 
Waguininho 
Bill

Colo-Colo:

Iván Morales
Rodrigo Echeverría 
Juan Martín Lucero 
Esteban Pavez 

Universidad de Chile:

Felipe Mora
Leandro Benegas 
Joaquín Larrivey 
Ángelo Araos 

Universidad Católica: 

Luciano Aued 
Diego Valencia
Fernando Zampedri 
Diego Buonanotte 

Unión Española: 

Iván Rossi 
Leandro Benegas 
Gonzalo Sosa
Cristián Palacios 

Santiago Wanderers:

Juan Ignacio Duma
Carlos Muñoz
Joaquín Pereyra
Matías Plaza

Deportes Iquique:

Álvaro Ramos
Edson Puch
Hans Salinas
Steffan Pino

Cobreloa:

Gustavo Gotti
Cristian Insaurralde
David Escalante
Bastián San Juan

Deportes Antofagasta:

Tobías Figueroa
Manuel López
Rodrigo Contreras
Jason Flores

Atlético Nacional:

Jefferson Duque
Dorlan Pabón
Óscar Perea
Eric Ramírez
Jader

Millonarios:

Leonardo Castro
Fernando Uribe
Beckham David Castro
Daniel Ruiz 
Santiago Giordana

América de Cali:

Adrián Ramos
Michael Barrios
Facundo Suárez
Edwin Cardona 

Junior:

Carlos Bacca
Steven Rodríguez
Brayan León
Deiber Caicedo

Cúcuta Deportivo:

Agustín Vuletich
Jonathan Agudelo
Luis Miranda
Jhonathan Agudelo

Deportes Quindío:

Wilson Carpintero
Juan Camilo Vela
Andrés Ibargüen
Jhonny Mosquera

Real Cartagena:

Juan José Salcedo
Edwin Aguilar
Luis Sandoval
Carlos Franco

Tigres FC:

Brayan Moreno
Luis Páez
Julián Quiñones
Jhon Fredy Salazar

Saprissa:

Juan Luis Mora
Rónald Matarrita 
Yendrick Ruiz
Ariel Rodríguez

Alajuelense:

Johan Venegas
José Guillermo Ortiz
Daniel Colindres
Ariel Lassiter

Herediano:

José Sánchez
Allan Miranda
Ariel Soto 
Daniel Colindres

Cartaginés:

Mauricio Solís
Júnior Díaz
Óscar Arroyo
Daniel Jiménez

Belén FC:

Bryan Isaías Vega 

Escorpiones:

Bryan Jiménez 
Abner Hidalgo 

Guanacasteca:

Johan Venegas 

Carmelita:

Joshua Parra 
Joshua Ulate 
Johnny Enrique Ruiz Castillo

Barcelona SC:

Damián Díaz
Cristian Colman
Gabriel Cortez 
Fidel Martínez

Emelec:

Pedro Quiñónez
Miller Bolaños
Kevin Rodríguez
Joao Rojas

LDU Quito:

Cristian Martínez Borja
José Angulo
Ángel Mena 
Jordy Alcívar

Independiente del Valle:

Lautaro Díaz
Gonzalo Plata 
Jhon Jairo Sánchez
Bryan Cabezas

Manta FC:

Daniel  Valencia
Richart  Ortiz
Ervin  Zorrilla 
Anderson  Castillo
Jostin  Alman
Joaquín  Salvucci
Darlin  Leiton

América de Quito:

Kevin  Hoyos 

El Nacional: 

Jhon  Cifuente

Chacaritas FC: 

Kevin  Valencia
Leonardo  Nazareno
Eder  Tandazo

Club América:

Henry  Martín
Brian  Rodríguez 

Chivas Guadalajara:

Armando  González 
Javier  Hernández 
Teun  Wilke
Hugo  Camberos

Cruz Azul:

Ángel  Sepúlveda
Giorgos  Giakoumakis 
Gabriel  Fernández 
Bryan  Gamboa  Galarza 
Ítalo  Cuesta 

Tigres UANL:

Nicolás  Ibáñez
Diego  Lainez

Atlante:

Vladimir Moragrega
Rafael Durán

Leones Negros:

Jesús Ocejo

Atlético Morelia:

Alonso Flores

Cancún FC:

Christopher Trejo
José Rodríguez

Olimpia:

Sebastián  Ferreira 
Derlis  González 
Hugo  Sandoval 
Adrián  Alcaraz 
Tiago  Caballero
Faustino  Barone

Cerro Porteño:

Juan  Iturbe 
Ignacio  Aliseda 
Pablo  Vegetti 
Ángel  Aguayo

Libertad:

Lorenzo  Melgarejo
Ivan  Franco

Guaraní:

Alan  Pereira 
Walter  González
Paul  Riveros
Juan  Santacruz

Sportivo Luqueño:

Walter González
Sergio Díaz
Alan Gustavo Pereira Guillén
Iván Gabriel Maggi

Sportivo San Lorenzo:

Antonio Oviedo Cortizo
Alex Junior Álvarez Rojas
Mathías Martínez
Elías Alderete

Atyrá FC:

Digno Javier González Sosa

Fernando de la Mora:

Fredy  Colmán
Santiago  Samuel  García  Giménez
Jonathan  Gómez
Jorge  Ariel  Quintana  Caballero

Alianza Lima:

Paolo Guerrero
Erick Castillo
Kevin Quevedo 
Gaspar Gentile

Universitario:

Alex Valera

Sporting Cristal:

Felipe Vizeu
Santiago González

FBC Melgar:

Jhonny Vidales
Bernardo Cuesta
Cristian Bordacahar 
Tomás Martínez

Juan Aurich:

Harrys Núñez
Eduardo Hernández 

Comerciantes Unidos:

Jhojan Domínguez
Maximiliano Lemos

Alianza Universidad:	

Brayan Guevara 

Santos FC:	

Federico Freire
Pietro Flores

LA Galaxy:

Joao Klauss
Gabriel Pec
Matheus Nascimento
Christian Ramirez 
Joseph Paintsil 
Ruben Ramos Jr

Inter Miami:

Lionel Messi 
Luis Suarez
Germán Berterame
Tadeo Allende
Mateo Silvetti

Seattle Sounders:

Jesús Ferreira 
Osaze De Rosario
Jordan Morris 
Paul Rothrock

Atlanta United:

Emmanuel Latte Lath
Miguel Almirón 
Sergio Santos

Louisville City FC:

Chris Donovan 
Ray Serrano
Tola Showunmi 
Jansen Wilson 
Evan Woodward

Sacramento Republic FC:

Juan Sebastián Herrera 
Cristian Parano 
Russell Cicerone

Tampa Bay Rowdies:

Manuel Arteaga 
Pacifique Niyongabire 
Juan Carlos Azócar

Phoenix Rising FC:

Collin Smith
Ihsan Sacko

Caracas FC:

Fernando Aristeguieta 
Lucciano Reinoso 
Lewuis Peña
Shola Oduoye 
Mauricio Márquez
Marco Biegel 
José Rondón

Deportivo Táchira:

Adalberto Peñaranda 
Rodrigo Pollero
Carlos Sosa 
José Balza
Jesús Duarte

Zamora FC:

Darwin Matheus 
Antonio Madreluis Romero
Erickson Yirson Gallardo

Monagas SC:

Fernando Basante
Franklin González 
Ronald José Rodríguez 
Juan Villalobos
Maelo Rentería 
Cristian Ramírez 
Leandro Josué Rodríguez Santaella
Victor Rivero
Edder Farías

Angostura FC:

Carlos Gorrochotegui 
Joaquín Zappacosta 
Yonaiker Martínez

Ureña SC:

Gilson Salazar 
Jesus Manuel Orozco Hernández 
Yerson Palencia

Titanes FC:

Dany Cure

Bolívar SC:

Ronald Arráez
Rafael Quiñones
Manuel Lugo 
Jesús Gamarra

Juventus FC:

Jonathan David 
Kenan Yıldız 
Dušan Vlahović
Edon Zhegrova 
Loïs Openda
Vasilije Adžić

Inter Milan:

Marcus Thuram 
Lautaro Martínez 
Pio Esposito 
Piotr Zieliński 
Joaquín Correa 
Marko Arnautović

AC Milan:

Rafael Leão 
Niclas Füllkrug
Santiago Giménez 
Christian Nkunku

SSC Napoli:

Rasmus Højlund
Lorenzo Lucca
Noah Okafor
Cyril Ngonge

Palermo:

Matteo Brunori 
Roberto Insigne 
Federico Di Francesco 
Joel Pohjanpalo
Thomas Henry
Jérémy Le Douaron 


Lecce:

Nikola Stulic 
Konan N’Dri
Francesco Camarda 
Riccardo Sottil
Santiago Pierotti
Walid Cheddira

Brescia:

Filippo Bianchi

Benevento:

Nicolò Francescotti 
Alejandro Gabriel Cichero

Paris Saint‑Germain:

Khvicha Kvaratskhelia
Gonçalo Ramos 
Ousmane Dembélé 
Désiré Doué

Marseille:

Mason Greenwood
Amine Gouiri 

Lyon:

Malick Fofana

AS Monaco:

Nahël Haddani
David Dunne 
David Balliana
Yannick Dodo

Toulouse:

Ilyas Azizi 
Thibo Nègre 
Noé Akpakoun 
Léo Frechingues 

Ajaccio:

Axel Strazel 
Bamalick Bella 
Léo Ghelfi 
Baptiste Colinet 

Valenciennes FC:

Edens Cadeau 
Youcef Hamiche 
Théo Dhollande 
Dayann Linyon 
Youssef Medani

Grenoble:

Sina Gassama 
Joany Bessou

FC Bayern Munich:

Harry Kane 
Michael Olise 
Luis Díaz 
Serge Gnabry 

Borussia Dortmund:

Serhou Guirassy 
Fábio Silva 
Maximilian Beier 
Karim Adeyemi 

RB Leipzig:

Conrad Harder 
Antonio Nusa 

Bayer Leverkusen:

Alejo Sarco
Patrik Schick
Aleix García

Hannover 96:

Benjamin Källman
Benedikt Pichler
Husseyn Chakroun
Mustapha Bundu

FC St. Pauli:

Kaars
Hountondji
Jones
Ceesay

Karlsruher SC:

Fabian Schleusener

1. FC Nürnberg:

Mohamed Zoma
Rafael Lubach

Real Madrid:

Kylian Mbappé
Vinícius Júnior 
Rodrygo 

FC Barcelona:

Ferran Torres 
Lamine Yamal 
Raphinha 
Robert Lewandowski

Atlético Madrid:

Antoine Griezmann
Giacomo Raspadori 

Sevilla FC:

Rafa Mir 
Kelechi Iheanacho
Alfon González 
Alexis Sánchez

RCD Espanyol:

Javier Puado Díaz 

Sporting de Gijón:

Juan Ferney Otero 
Jonathan Dubasin

RCD Mallorca:

Vedat Muriqi

Girona FC:

V. Vanat 
Bryan Gil 
Viktor Tsygankov 
Y. Asprilla
Cristhian Stuani

Manchester United:

Bryan Mbeumo 
Matheus Cunha 
Benjamin Šeško

Liverpool FC:

Hugo Ekitike 
Federico Chiesa 
Cody Gakpo 

Chelsea FC:

João Pedro 

Arsenal FC:

Viktor Gyökeres 
Noni Madueke

West  Bromwich  Albion:

Heggebø 

Bristol City:

Emil Riis

Hull City:

Oli  McBurnie 
Mohamed  Belloumi
Liam  Millar 

Sunderland:

Brian Brobbey 
Iliman Ndiaye 
Amad 
Eliezer Mayenda

Celtic FC:

Daizen Maeda
Kyogo Furuhashi 
Jota
Adam Idah 
Benjamin Nygren 

Rangers FC:

Youssef Chermiti 

Aberdeen FC:

Jayden Nisbet 

Hearts:

Lawrence Shankland 
Cláudio Braga 
Vargas 
Kabangu
Wilson

Dundee FC:

Murray

Queen of the South FC:

Kai Kennedy
Kurtis Guthrie
Cole Burke 
Liam Smith 
Euan Ross
Matt Hall 
Freddie O'Donoghue

Raith Rovers FC:

Lewis Vaughan
Jack Hamilton
Andy Winter

Partick Thistle FC: 

Logan Chalmers
Tony Watt 
Alex Samuel 
Daniel O’Reilly
Ricco Diack

Olympiacos FC:

Ayoub El Kaabi
Mehdi Taremi 
Daniel Podence
Gelson Martins
Clayton

Panathinaikos FC:

Karol Świderski

AEK Athens FC:

Luka Jović 
Anthony Martial

PAOK FC:

Giorgos Giakoumakis 
Fedor Chalov 
Andrija Živković 
Kiril Despodov 

Aris FC:

Loren Morón 
Yannis Gianniotas 
Carles Pérez 
Tino Kadewere 
Dudu 

Atromitos FC:

Giorgos Tzovaras 
Ognjen Ožegović 
Aitor García Flores 

Lamia FC:

Alexandros Tereziou 
Anestis Vlachomitros 
Toshio Lake

Volos FC:

Lazaros Lamprou 
Maximiliano Comba 
Nacho Gil 
Juan Pablo Añor

FC Copenhagen:

Mohamed Elyounoussi 
Jordan Larsson 
Youssoufa Moukoko 
Viktor Bjarki Daðason 

FC Midtjylland:

Franculino Djú
Júnior Brumado 
Cho Gue‑sung

Brøndby IF:

Nicolai Vallys

AaB (Aalborg BK):

Kelvin John 
Nicklas Helenius 
Kornelius Hansen 
Oliver Ross 
Amar Diagne 

Vejle BK:

Amin Chiakha 

Viborg FF:

Charly Nouck 

Silkeborg IF:

Younes Bakiz 
Callum McCowatt 
Alexander Simmelhack 

FC Fredericia:

Gustav Marcussen 
Emilio Simonsen 
Moses Opondo

Club Brugge KV:

Christos Tzolis 
Nicolò Tresoldi 
Romeo Vermant 

RSC Anderlecht:

Thorgan Hazard 
Nilson Angulo

KRC Genk:

Hyeon‑gyu Oh 
Daan Heymans 

Standard Liège:

Thomas Henry

Lommel SK:

Ralf Seuntjens

RWDM Brussels:

Gaëtan Robail

KVC Westerlo:

Nacho Ferri 
Allahyar Sayyadmanesh 
Eliot Bujupi 
Antoñito Cordero 

RFC Seraing:

Édouard Soumah‑Abbad 
Abdoulaye Agne Ba 
Hemsley Akpa‑Chukwu 
Nabil Bouchentouf

Ludogorets Razgrad:

Mamadou Diallo 
Leandro Godoy 
Bertrand Fourrier 

CSKA Sofia:

Duckens Nazon 
Brayan Moreno 

Levski Sofia:

Armstrong Oko‑Flex 

Botev Plovdiv:

Todor Nedelev 

Montana:

Boris Dimitrov 
Philip Ejike 

Botev Vratsa:

Martin Petkov 

Septemvri Sofia:

Bertrand Fourrier 
Borislav Rumenov Marinov 
Nikola Velichkovski
Aleksandar Dzhamov

Pirin Blagoevgrad:

Nicholas Penev 

Dinamo Zagreb:

Sandro Kulenović 
Dion Drena Beljo 
Arbër Hoxha 

Hajduk Split:

Michele Šego 

HNK Rijeka:

Toni Fruk 

NK Osijek:

Nail Omerović

Šibenik:

Vinko Rozić 
Stjepan Lončar 

Istra 1961

Vinko Rozić 
Stjepan Lončar 

Cibalia:

Gabrijel Boban 
Antonio Blažanović 
Leandro Samper Caimanque 
Matej Lugaric 
Petar Mišić 

Hrvatski Dragovoljac:

Lovre Čirjak 
Mihael Stipić




Sydney FC:

Al Hassan Toure 
Joe Lolley
Tiago Quintal
Patrick Wood 
Víctor Campuzano 

Melbourne City FC:

Max Caputo 
Medin Memeti

Brisbane Roar FC:

Chris Long

Western Sydney Wanderers FC:

Kosta Barbarouses
Ryan Fraser
Brandon Borrello 
Bozhidar Kraev 
Alex  Bonetig

Perth Glory Youth:

Sebastian Despotovski
Daniel Jankuloski
Adam Bugarija
Giovanni De Abreu

Melbourne Victory Youth:

Luis Lawrie‑Lattanzio
Birkan Kirdar
Joshua Varga

Sydney FC Youth:

Marco Tilio 

Brisbane Roar Youth:

Daniel Leck
Mirza Muratovic

Kossa FC:

Alden Suri 
Philimon Talisia 
Besa Zopia 
Winford Norman 

Solomon Warriors:

Dennis Ifunaoa 
Molea Tigi 
Gagame Feni 

Marist FC:

Norman Ngafu

Henderson Eels:

Joses Nawo 

AS Magenta:

Jean‑Philippe Saïko 

Hienghène Sport:

Bertrand Kaï 
Antony Kai 
Antoine Roine 
Emmanuel Boawane Kayara 

AS Mont‑Dore:

Kapone Emmanuel Lambert Xulue 

AS Lössi:

Jean‑Philippe Saïko

Team Wellington:

Hamish Watson
Sam Mason‑Smith
Andy Bevin
Jack‑Henry Sinclair

Auckland City:

Logan Rogerson
Myer Bevan

Wellington Phoenix Reserves:

Riley Bidois
Luke Supyk
Fergus Gillion

Hawke’s Bay United:

Jorge Akers
Ahinga Selemani


